language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - git submodule update --init --recursive

install:
  - pip install -e .
  - pip install pyflakes
  - pip install pep8

script: 
  - python setup.py test
  - pyflakes setup.py sass
  - pep8 setup.py sass
